embedding_size: 64
weight_dim: 10
atten_dim: 32
num_bit_conv: 32
num_vec_conv: 8
message_drop_list: [0.7, 0.7, 0.7]
hidden_size_list: [64, 64, 64]
neighbor_k: 25
margin: 1
mul_loss_func: "logsigmoid"

node_dropout: 0.1
message_dropout: 0.1
reg_weight: 1e-2
transtag_weight: 1e-02